### ISSUE TITLE
4.0.0 Release | zabbix reports mariadb server is down

### ISSUE THREAD

**Issue by radarsymphony** [tiredofit/docker-mariadb#23]
Hi tiredofit,

I recently started testing and updating my tiredofit/mariadb:10.8 to your latest 4.0 series.

Upon start up, our zabbix monitoring system reports that the MariaDB server is down.

Testing with the following compose.yml

```
version: '3.7'

services:
  example-db:
    image: tiredofit/mariadb:10.8
    stop_grace_period: 3m
    container_name: example-db
    volumes:
      #- ./dbbackup:/backup
      - ./db:/var/lib/mysql
      - ./logs:/logs
    environment:
      - TIMEZONE=America/Vancouver
      - CONTAINER_NAME=example-db

      - ROOT_PASS=rootpassword

      - DB_NAME=database
      - DB_USER=user
      - DB_PASS=password

      - DEBUG_MODE=TRUE

    networks:
      - services
    restart: always

networks:
  services:
    external: true
```

In the container:

```
[tiredofit/mariadb:10.8:10.8-4.0.0 18:00:37 /] $ ps -ef
PID   USER     TIME  COMMAND
    1 root      0:00 /package/admin/s6/command/s6-svscan -d4 -- /run/service
   18 root      0:00 s6-supervise s6-linux-init-shutdownd
   20 root      0:00 /package/admin/s6-linux-init/command/s6-linux-init-shutdownd -c /run/s6/basedir -g 3000 -C -B
   26 root      0:00 s6-supervise s6rc-oneshot-runner
   27 root      0:00 s6-supervise s6rc-fdholder
   34 root      0:00 /package/admin/s6/command/s6-ipcserverd -1 -- /package/admin/s6/command/s6-ipcserver-access -v0 -E -l0 -i data/rules -- /package/admin/s6/command/s6-sudod -t 30000 -- /pa
 1619 root      0:00 s6-supervise 03-monitoring
 1621 root      0:00 s6-supervise 04-scheduling
 1622 root      0:00 s6-supervise 10-mariadb
 1623 root      0:00 /usr/sbin/crond -f -l 8 -L /var/log/cron//cron.log
 1624 mariadb   0:00 /usr/bin/mysqld --console
 1625 zabbix    0:00 zabbix_agent2 -c /etc/zabbix//zabbix_agentd.conf -f
 2030 root      0:00 bash
 2037 root      0:00 ps -ef
```

Our zabbix system is running your `tiredofit/zabbix:3.1.24`
- ZABBIX_VERSION=6.2.6
- PHP_BASE=8.0

Are you able to indicate if I'm missing a required environment variable for this to report that the Mariadb server is running? Do you have any ideas for why this image might not be starting up correctly for me? 

Can I provide additional information that would be helpful for debugging?
