### ISSUE TITLE
MariaDB Initializing scripts appear to be missing

### ISSUE THREAD

**Issue by teknobilly** [tiredofit/docker-mariadb#5]
When starting a new database container, logs show:
```
bbabdev-db           | [cont-init.d] 10-mariadb: executing... 
bbabdev-db           | ** [mariadb] error: database is uninitialized and MYSQL_ROOT_PASSWORD not set
bbabdev-db           |     Did you forget to add -e MYSQL_ROOT_PASSWORD=... ?
bbabdev-db           | [cont-init.d] 10-mariadb: exited 1.
```

bbabdev-db defined in docker-compose as:
```
 bbabdev-db:
    image: tiredofit/mariadb
    container_name: bbabdev-db
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - ROOT_PASS=aogfjghaig1
      - DB_NAME=wordpress
      - DB_USER=wordpress
      - DB_PASS=aogfjghaig

      - ZABBIX_HOSTNAME=bbabdev-db
    networks:
      - services
    restart: always
```

I can add the environment variable for MYSQL_ROOT_PASSWORD and the initial startup continues successfully.   The issue is that DB_USER is not created as a user in the Database.  Breaking the WordPress container that relies on DB_USER being there.

The creation script that assigns the ROOT_PASS to MYSQL_ROOT_PASSWORD, and creates DB_USER appears to be missing. 

Can you add that back in please :)

Thanks Dave, much appreciated.
